### ISSUE TITLE
FAILED TO CREATE ACCOUNT: list index out of range

### ISSUE THREAD

**Issue by PM-ME-BUMBLEBEES** [SeanDaBlack/KelloggBot#52]
I'm on a mac, I have everything installed and set up. When I run the bot, and it goes to create an account, I get this error message: FAILED TO CREATE ACCOUNT: list index out of range

What am I doing wrong?

**Comment by bolshoytoster** [comment]
If you change the
```python
        try:
            generate_account(driver, fake_identity)
        except Exception as e:
            printf(f"FAILED TO CREATE ACCOUNT: {e}")
            pass
```
to 
```python
#        try:
        generate_account(driver, fake_identity)
#        except Exception as e:
#            printf(f"FAILED TO CREATE ACCOUNT: {e}")
#            pass
```
Notice there are 4 spaces removed before `generate_account(driver, fake_identity)`, you should get the full stack trace.

If you get the error again can you post the full error please.

**Comment by PM-ME-BUMBLEBEES** [comment]
Here is the full traceback:

Traceback (most recent call last):
  File "/Users/annabrown/Desktop/KelloggBot-main/main.py", line 297, in <module>
    main()
  File "/Users/annabrown/Desktop/KelloggBot-main/main.py", line 279, in main
    generate_account(driver, fake_identity)
  File "/Users/annabrown/Desktop/KelloggBot-main/main.py", line 158, in generate_account
    solveCaptcha(driver)
  File "/Users/annabrown/Desktop/KelloggBot-main/main.py", line 66, in solveCaptcha
    googleClass = driver.find_elements_by_class_name(CAPTCHA_BOX)[0]
IndexError: list index out of range

**Comment by bolshoytoster** [comment]
Ah, that'll be because they just removed the recaptcha, also this repo currently doesn't work because they just added email verification which this repo doesn't handle for.

If you can clone [my repo](https://github.com/bolshoytoster/KelloggBot) instead, that should hopefully get around it.
