### ISSUE TITLE
Maybe I'm just being dumb, but could I please have a hand?

### ISSUE THREAD

**Issue by PokemonHacker1337** [SeanDaBlack/KelloggBot#61]
So I was trying to install and run KelloggBot, and I believe I have everything set up, all the files in the proper PATH, and such. Upon running python main.py in CMD, I get this:

`DevTools listening on ws://127.0.0.1:1684/devtools/browser/68f9b174-8099-4da8-80d1-689e36fae52b
FAILED TO START DRIVER: Message: session not created: This version of ChromeDriver only supports Chrome version 87
Current browser version is 96.0.4664.110 with binary path C:/Users/%username%/AppData/Local/Google/Chrome/Application/chrome.exe

USING GUERRILLA TO CREATE EMAIL
EMAIL CREATED
FAILED TO CREATE ACCOUNT: local variable 'driver' referenced before assignment
FAILED TO FILL OUT APPLICATION AND SUBMIT: local variable 'driver' referenced before assignment
Traceback (most recent call last):
  File "C:\Users\\%username%\Downloads\KelloggBot-main\main.py", line 276, in main
    fill_out_application_and_submit(driver, random_city, fake_identity)
UnboundLocalError: local variable 'driver' referenced before assignment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\\Users\\%username%\Downloads\KelloggBot-main\main.py", line 288, in <module>
    main()
  File "C:\\Users\\%username%\Downloads\KelloggBot-main\main.py", line 280, in main
    driver.close()
UnboundLocalError: local variable 'driver' referenced before assignment`

I'm not sure what they are referring to by Chrome version 87. I do have an old version of Chrome for playing Flash games still, installed as a portable version in my downloads folder. 

Sorry for the dumb question, but I was wondering if I could have a hand. Thanks, I hope you have a great rest of the day, whoever is reading this :-)

**Comment by bolshoytoster** [comment]
It looks like `ChromeDriverManager` got confused by the multiple versions of chrome. A workaround is to add `version="96.0.4664.110"` to `main.py` in the `start_driver` function at lines 56 && 59:
https://github.com/SeanDaBlack/KelloggBot/blob/11a9218d04d7d26f6e124b45062b5e961a52ec72/main.py#L55-L60
In both cases of `ChromeDriverManager().install()`, add `version="96.0.4664.110"` like so:
```python
ChromeDriverManager(version="96.0.4664.110").install()
```
It should work.

**Comment by demarcusw** [comment]
> 

That version is not found on macOS for whatever reason. Got the following error:

`FAILED TO START DRIVER: There is no such driver by url https://chromedriver.storage.googleapis.com/96.0.4664.110/chromedriver_mac64.zip`

This did work however:

`ChromeDriverManager(version="96.0.4664.45").install()`
* https://chromedriver.storage.googleapis.com/index.html?path=96.0.4664.45/

**Comment by PokemonHacker1337** [comment]
Like this?
```
        driver = webdriver.Chrome(ChromeDriverManager(version="96.0.4664.110").install(),options=options)
        driver.set_window_size(1440, 900)
    elif (args.debug == DEBUG_ENABLED):
        driver = webdriver.Chrome(ChromeDriverManager(version="96.0.4664.110").install())
```

I got the same error, so I decided to just delete the portable version of Chrome to stop confusing the program, and I got this:

`FAILED TO START DRIVER: There is no such driver by url https://chromedriver.storage.googleapis.com/96.0.4664.110/chromedriver_win32.zip
USING GUERRILLA TO CREATE EMAIL
EMAIL CREATED
FAILED TO CREATE ACCOUNT: local variable 'driver' referenced before assignment
FAILED TO FILL OUT APPLICATION AND SUBMIT: local variable 'driver' referenced before assignment
Traceback (most recent call last):
  File "C:\Users\%username%\Downloads\KelloggBot-main\main.py", line 276, in main
    fill_out_application_and_submit(driver, random_city, fake_identity)
UnboundLocalError: local variable 'driver' referenced before assignment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\%username%\Downloads\KelloggBot-main\main.py", line 288, in <module>
    main()
  File "C:\Users\%username%\Downloads\KelloggBot-main\main.py", line 280, in main
    driver.close()
UnboundLocalError: local variable 'driver' referenced before assignment`

**Comment by bolshoytoster** [comment]
@PokemonHacker1337
Refer to @demarcusw's answer:

> > 
> 
> That version is not found on macOS for whatever reason. Got the following error:
> 
> `FAILED TO START DRIVER: There is no such driver by url https://chromedriver.storage.googleapis.com/96.0.4664.110/chromedriver_mac64.zip`
> 
> This did work however:
> 
> `ChromeDriverManager(version="96.0.4664.45").install()`
> 
> * https://chromedriver.storage.googleapis.com/index.html?path=96.0.4664.45/

It's my fault for not checking the url first, you should use `version="96.0.4664.45"` instead.

**Comment by PokemonHacker1337** [comment]
I did do that. The same thing happened, so I decided to just download a fresh copy and try again, and I partially got it working, at least until I ran into a new problem. Should I describe the new problem here, or do I open a new issue? Sorry, I'm new to GitHub.

**Comment by bolshoytoster** [comment]
@PokemonHacker1337
> I did do that. The same thing happened, so I decided to just download a fresh copy and try again, and I partially got it working, at least until I ran into a new problem. Should I describe the new problem here, or do I open a new issue? Sorry, I'm new to GitHub.

Normally it'd probably be best to open a new issue, but you may as well post it here now.

**Comment by PokemonHacker1337** [comment]
I appreciate the help @bolshoytoster. 

I wanted to watch it in debug mode to see what happens in real time, so I enabled the --debug switch, just for fun. When the program got to the part of the website where it was waiting to hear back from the email by giving a 1 time use password, it eventually threw an error and gave up. It claims that it cannot find a file, but I'm unsure which file they are talking about.

`DevTools listening on ws://127.0.0.1:1178/devtools/browser/7394298a-6320-43d5-80b8-9375c43aaa70
[12840:6796:1218/195334.023:ERROR:chrome_browser_main_extra_parts_metrics.cc(226)] crbug.com/1216328: Checking Bluetooth availability started. Please report if there is no report that this ends.
[12840:6796:1218/195334.025:ERROR:chrome_browser_main_extra_parts_metrics.cc(229)] crbug.com/1216328: Checking Bluetooth availability ended.
[12840:4972:1218/195334.025:ERROR:device_event_log_impl.cc(214)] [19:53:34.025] USB: usb_device_handle_win.cc:1048 Failed to read descriptor from node connection: A device attached to the system is not functioning. (0x1F)
[12840:6796:1218/195334.026:ERROR:chrome_browser_main_extra_parts_metrics.cc(232)] crbug.com/1216328: Checking default browser status started. Please report if there is no report that this ends.
[12840:4972:1218/195334.027:ERROR:device_event_log_impl.cc(214)] [19:53:34.027] USB: usb_device_handle_win.cc:1048 Failed to read descriptor from node connection: A device attached to the system is not functioning. (0x1F)
[12840:6796:1218/195334.037:ERROR:chrome_browser_main_extra_parts_metrics.cc(236)] crbug.com/1216328: Checking default browser status ended.
USING GUERRILLA TO CREATE EMAIL
EMAIL CREATED
successfully made account for fake email hoovercasey@yahoo.com
FAILED TO FILL OUT APPLICATION AND SUBMIT: [WinError 2] The system cannot find the file specified`

**Comment by bolshoytoster** [comment]
At `main.py`, line 276:

https://github.com/SeanDaBlack/KelloggBot/blob/11a9218d04d7d26f6e124b45062b5e961a52ec72/main.py#L275-L281

Can you replace that with just:
```python
    fill_out_application_and_submit(driver, random_city, fake_identity) 
```

Notice that the line is indented by only 4 spaces rather than 8.

This will allow you to get the full stack trace, if you get the error again can you post the full error please.

**Comment by PokemonHacker1337** [comment]
I have followed those directions, and it works quite a bit more. The first 2 that it did worked perfectly fine, assuming that it is supposed to end once it says that it successfully made an account for the fake email. 
`DevTools listening on ws://127.0.0.1:1057/devtools/browser/5359d608-a4ec-4cfe-8b3c-afc0423f8f61
[13516:11096:1218/203202.782:ERROR:chrome_browser_main_extra_parts_metrics.cc(226)] crbug.com/1216328: Checking Bluetooth availability started. Please report if there is no report that this ends.
[13516:11096:1218/203202.783:ERROR:chrome_browser_main_extra_parts_metrics.cc(229)] crbug.com/1216328: Checking Bluetooth availability ended.
[13516:7764:1218/203202.783:ERROR:device_event_log_impl.cc(214)] [20:32:02.782] USB: usb_device_handle_win.cc:1048 Failed to read descriptor from node connection: A device attached to the system is not functioning. (0x1F)
[13516:11096:1218/203202.784:ERROR:chrome_browser_main_extra_parts_metrics.cc(232)] crbug.com/1216328: Checking default browser status started. Please report if there is no report that this ends.
[13516:7764:1218/203202.784:ERROR:device_event_log_impl.cc(214)] [20:32:02.783] USB: usb_device_handle_win.cc:1048 Failed to read descriptor from node connection: A device attached to the system is not functioning. (0x1F)
[13516:11096:1218/203202.795:ERROR:chrome_browser_main_extra_parts_metrics.cc(236)] crbug.com/1216328: Checking default browser status ended.
USING GUERRILLA TO CREATE EMAIL
EMAIL CREATED
successfully made account for fake email lindseygeorge@gmail.com

DevTools listening on ws://127.0.0.1:1227/devtools/browser/d78254ee-64e7-4435-b8b4-b9edcfe08ba9
[7788:2980:1218/203401.284:ERROR:chrome_browser_main_extra_parts_metrics.cc(226)] crbug.com/1216328: Checking Bluetooth availability started. Please report if there is no report that this ends.
[7788:2980:1218/203401.285:ERROR:chrome_browser_main_extra_parts_metrics.cc(229)] crbug.com/1216328: Checking Bluetooth availability ended.
[7788:6796:1218/203401.285:ERROR:device_event_log_impl.cc(214)] [20:34:01.285] USB: usb_device_handle_win.cc:1048 Failed to read descriptor from node connection: A device attached to the system is not functioning. (0x1F)
[7788:2980:1218/203401.285:ERROR:chrome_browser_main_extra_parts_metrics.cc(232)] crbug.com/1216328: Checking default browser status started. Please report if there is no report that this ends.
[7788:6796:1218/203401.286:ERROR:device_event_log_impl.cc(214)] [20:34:01.286] USB: usb_device_handle_win.cc:1048 Failed to read descriptor from node connection: A device attached to the system is not functioning. (0x1F)
[7788:2980:1218/203401.296:ERROR:chrome_browser_main_extra_parts_metrics.cc(236)] crbug.com/1216328: Checking default browser status ended.
USING GUERRILLA TO CREATE EMAIL
EMAIL CREATED
successfully made account for fake email jeffreysanchez@yahoo.com`

The above 2 are attempts where it worked perfectly. After this is where it tripped up and it left me on the Kellogg's registration screen. 

`DevTools listening on ws://127.0.0.1:1615/devtools/browser/997a7179-0c4c-4e3c-a400-d38072473e4b
[15680:2136:1218/203557.365:ERROR:chrome_browser_main_extra_parts_metrics.cc(226)] crbug.com/1216328: Checking Bluetooth availability started. Please report if there is no report that this ends.
[15680:2136:1218/203557.366:ERROR:chrome_browser_main_extra_parts_metrics.cc(229)] crbug.com/1216328: Checking Bluetooth availability ended.
[15680:15508:1218/203557.366:ERROR:device_event_log_impl.cc(214)] [20:35:57.366] USB: usb_device_handle_win.cc:1048 Failed to read descriptor from node connection: A device attached to the system is not functioning. (0x1F)
[15680:2136:1218/203557.367:ERROR:chrome_browser_main_extra_parts_metrics.cc(232)] crbug.com/1216328: Checking default browser status started. Please report if there is no report that this ends.
[15680:15508:1218/203557.368:ERROR:device_event_log_impl.cc(214)] [20:35:57.367] USB: usb_device_handle_win.cc:1048 Failed to read descriptor from node connection: A device attached to the system is not functioning. (0x1F)
[15680:2136:1218/203557.378:ERROR:chrome_browser_main_extra_parts_metrics.cc(236)] crbug.com/1216328: Checking default browser status ended.
USING GUERRILLA TO CREATE EMAIL
Traceback (most recent call last):
  File "C:\Users\%username%\Downloads\KelloggBot-main\main.py", line 282, in <module>
    main()
  File "C:\Users\%username%\Downloads\KelloggBot-main\main.py", line 249, in main
    response = requests.get('https://api.guerrillamail.com/ajax.php?f=get_email_address').json()
  File "C:\Users\%username%\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\models.py", line 910, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Users\%username%\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\%username%\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\%username%\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)`

Thanks for the patience by the way, it truly means a lot.

**Comment by bolshoytoster** [comment]
@PokemonHacker1337 
> json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

It looks like a call to `api.guerrillamail.com` fails.

I've fixed this on [my fork](https://github.com/bolshoytoster/KelloggBot) if you want to download that instead and I have a related pull request (#62). If you don't want to, a workaround would be to run `main.py` from the command line with `--mailtm` to use mail.tm instead of guerrillamail.

**Comment by PokemonHacker1337** [comment]
So far, I left the fork running for a few minutes, and I haven't seen any issues. I'll get back to you if I have any issues with the fork. Thanks for the help.
